import { Assistant } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: 'Tribewearclub',
  description: 'Generated by create next app',
  icons: "./favicon.ico"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
  
      <body className={inter.className}>

            {children}

      </body>
    </html>
  )
}
